apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod3
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: example-pvc-file
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
