all:
  hosts:
    host1.example.com:
  children:
    webservers:
      hosts:
        host2.example.com:
        192.168.1.219:
    databases:
      hosts:
        host3.example.com:
        host4.example.com:
